# Generated by Django 3.2 on 2022-03-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
