# Generated by Django 3.2 on 2022-02-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profiles',
            new_name='user_profile',
        ),
    ]
